### PR TITLE
Gcorr

### PR DESCRIPTION
**Pull request by sher-s**
I have tested non-null gcorr code using both my local machine (using created independent example maps and masks) and feynman(for slurm related jobs).

### CODE REVIEW

**Review by annegambrel — CHANGES_REQUESTED** [review]
This is great! To summarize my feedback:
I think it would be best to merge the signal and null versions into a single set of scripts, and then have gcorr_config_null.ini and gcorr_config_signal.ini that take care of having two data roots/setting things that all the scripts use (like map tags), etc. And then when doing the computation of gcorr, have both take the average fisher matrix like you do for nulls (no ensemble mean run for non-nulls), then fit the histogrammed null qbs to a gaussian (already implemented for eb/tb for non-nulls) and fit the non-null qbs to a log-normal distribution, as is already done. I think this would just have less code duplication and be easier to follow.

Let me know if that makes sense/if you have other thoughts.

**Comment by annegambrel** [comment]
> This is great! To summarize my feedback:
> I think it would be best to merge the signal and null versions into a single set of scripts, and then have gcorr_config_null.ini and gcorr_config_signal.ini that take care of having two data roots/setting things that all the scripts use (like map tags), etc. And then when doing the computation of gcorr, have both take the average fisher matrix like you do for nulls (no ensemble mean run for non-nulls), then fit the histogrammed null qbs to a gaussian (already implemented for eb/tb for non-nulls) and fit the non-null qbs to a log-normal distribution, as is already done. I think this would just have less code duplication and be easier to follow.
> 
> Let me know if that makes sense/if you have other thoughts.

One more thing I forgot-- signal and null gcorrs should be written to files with different names (maybe just an additional _null tag for nulls) and then code should be implemented in xfaster_class that loads the right one depending on if null=True.

**Review by annegambrel — COMMENTED** [review]
I refactored things such that now:
* signal and null can be run using the same code, just a different config file
* A user just makes a config file, does run_xfaster.py once for the initial run, and then just iterate.py over and over after that-- no symlinking or copying things or running compute_gcorr.py.

@sher-s if you could especially look at the null test stuff and make any changes you see fit for that, that'd be super helpful. I've tested on signal and things are working fine so I'm done editing.

**Comment by arahlin** [comment]
A couple thoughts:

1. Remove the `gcorr` directory if it's been superceded by `scripts/gcorr`.
2. I think it might make sense to combine all three scripts into one, with functions for each of the steps that are now split into separate scripts, and maybe using argparse subparsers to run it in different modes if necessary.  Fewer files to think about, and a single call to run iterations until some convergence criterion is met.
3. Can we make this work on not-a-cluster too?  E.g. using a multiprocessing pool to spawn instances of the run script in the right mode.

**Review by annegambrel — APPROVED** [review]

**Pull request merged**
